class Strings{
  static const String ENABLED = "Enabled";
  static const String NEEDS = "Needs";
  static const String CUSTOM = "Custom";
  static const String KEYBOARD = "Keyboard";
  static const String CONTACTS = "Contacts";
  static const String SMART = "Smart";
  static const String EMERGENCY = "Emergency";
  static const String HOME = "Home";
  static const String DOWN = "Down";
  static const String RIGHT = "Right";
  static const String ENTER = "Enter";
  static const String BACK = "Back";
  static const String HUE = "Philips Hue";
  static const String CHROMECAST = "Chromecast";
  static const String HYGIENE = "Hygiene";
  static const String EMOTIONS = "Emotions";
  static const String ROOMS = "Rooms";
  static const String FOOD_DRINK = "Food and drinks";
  static const String HUNGRY = "Hungry";
  static const String THIRSTY = "Thirsty";
  static const String SNACKS = "Snacks";
  static const String TOILET = "Toilet";
  static const String SHOWER = "Shower";
  static const String BATH = "Bath";
  static const String MEDICATION = "Medication";
  static const String HAPPY = "Happy";
  static const String SAD = "Sad";
  static const String ANGRY = "Angry";
  static const String TIRED = "Tired";
  static const String SCARED = "Scared";
  static const String SURPRISED = "Surprised";
  static const String OUTSIDE = "Outside";
  static const String LIVING_ROOM = "Living room";
  static const String KITCHEN = "Kitchen";
  static const String BEDROOM = "Bedroom";
  static const String BASEMENT = "Basement";

}
